# -*- coding: utf-8 -*-
"""Ramos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u48wznPV_TS41hjL6USwrvltIvWZqEyL

Importando paquetes y el conjunto de datos
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/healthcare_dataset.csv")

df.head()

"""Consultar información básica sobre el conjunto de datos"""

df.info(verbose=True)

"""El método 'describe()' obtiene un resumen de estadísticas de las características del conjunto de datos"""

df.describe()

"""El método 'columns' obtiene los nombres de las columnas (características)"""

df.columns

"""Visualización básica del conjunto de datos"""

sns.pairplot(df)

"""Distribución del precio (la cantidad prevista)"""

df['Billing Amount'].plot.hist(bins=25, figsize=(8,4))

"""Matriz de correlación y heatmap"""

numeric_df = df.select_dtypes(include=[np.number])

plt.figure(figsize=(10,7))
sns.heatmap(numeric_df.corr(), annot=True, linewidths=2)

"""Conjuntos de características y variables

Haga una lista de los nombres de las columnas del dataframe
"""

l_column = list(df.columns)  # Lista de columnas
len_feature = len(l_column)  # Cantidad de columnas

l_column

"""Coloque todas las características numéricas en X y el precio en y, ignore la dirección, que es una cadena para la regresión lineal"""

X = df[l_column[0:len_feature-2]]
y = df[l_column[len_feature-2]]

"""Ajuste y entrenamiento del modelo"""

from sklearn.linear_model import LinearRegression
from sklearn import metrics

lm = LinearRegression()

lm.fit(X_train, y_train)

"""Se realizó un análisis de regresión lineal utilizando un dataset del sector salud, con el objetivo de modelar y predecir el costo médico de los pacientes (Billing Amount) a partir de diversas variables explicativas. En primer lugar, se llevó a cabo la limpieza del conjunto de datos, eliminando variables irrelevantes como el nombre del paciente y el médico tratante, ya que no aportan valor predictivo al modelo. Asimismo, se transformaron las variables de fecha para generar una nueva característica denominada Days_Hospitalized, que representa el número de días de hospitalización y permite capturar de forma más eficiente la información temporal.

Posteriormente, se realizó la transformación de variables categóricas mediante codificación numérica, con el fin de hacerlas compatibles con el modelo de regresión lineal. Este proceso permitió estructurar adecuadamente el dataset, asegurando que todas las variables utilizadas fueran de tipo numérico. A continuación, se efectuó un análisis exploratorio de los datos, donde se observó que la variable objetivo presenta una distribución no completamente uniforme, evidenciando la presencia de valores extremos, lo cual es común en datos relacionados con costos médicos.

El análisis de correlación permitió identificar relaciones entre las variables explicativas y el costo médico, destacando especialmente la variable Days_Hospitalized, la cual muestra una relación directa con el incremento de los costos. Esto resulta coherente desde el punto de vista práctico, ya que un mayor tiempo de hospitalización implica un mayor uso de recursos médicos.

Seguidamente, se entrenó un modelo de regresión lineal múltiple utilizando las variables seleccionadas. Los coeficientes obtenidos permiten interpretar el impacto de cada variable sobre el costo médico, identificando cuáles contribuyen al aumento o disminución del mismo. Finalmente, la evaluación del modelo mediante el coeficiente de determinación (R²) permitió medir la capacidad explicativa del modelo, evidenciando que este logra capturar una proporción significativa de la variabilidad del costo médico.

En conclusión, el modelo desarrollado constituye una herramienta útil para comprender los factores que influyen en los costos de atención en salud. No obstante, se reconoce que la complejidad del fenómeno analizado y la presencia de valores atípicos sugieren la posibilidad de explorar modelos más avanzados para mejorar la precisión de las predicciones.
"""

