# -*- coding: utf-8 -*-
"""Regresion_Lineal_Proyectos_jeyson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I90KjVpL8FzvN64Qga0xZdJp5G1837yV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# =========================
# 1. CARGAR DATASET
# =========================
df = pd.read_csv("https://github.com/ulewis/Ejemplos/raw/main/Datos/healthcare_dataset.csv")

# =========================
# 2. GRAFICO ANTES
# =========================
plt.figure(figsize=(8,5))
plt.scatter(df["Age"], df["Billing Amount"])
plt.xlabel("Age")
plt.ylabel("Billing Amount")
plt.title("ANTES: Edad vs Costo")
plt.show()

# =========================
# 3. SELECCIÓN VARIABLES
# =========================
df_model = df[[
    "Age",
    "Gender",
    "Medical Condition",
    "Admission Type",
    "Insurance Provider",
    "Billing Amount"
]]

# One Hot Encoding
df_model = pd.get_dummies(df_model, drop_first=True)

# =========================
# 4. X y y
# =========================
X = df_model.drop("Billing Amount", axis=1)
y = df_model["Billing Amount"]

# =========================
# 5. TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 6. MODELO

lm = LinearRegression()
lm.fit(X_train, y_train)


# 7. PREDICCION

y_pred = lm.predict(X_test)

# 8. EVALUACION

print("R2:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

# =========================
# 9. GRAFICO DESPUES
# =========================
plt.figure(figsize=(8,5))
plt.scatter(y_test, y_pred, alpha=0.5)

plt.xlabel("Real")
plt.ylabel("Predicho")
plt.title("DESPUÉS: Real vs Predicho")

# línea ideal
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red")

plt.show()

# 10. RESIDUALES

residuals = y_test - y_pred

plt.figure(figsize=(8,4))
plt.hist(residuals, bins=30)
plt.title("Errores del modelo")
plt.show()


# 11. COEFICIENTES

coef_df = pd.DataFrame()
coef_df["Variable"] = X.columns
coef_df["Coeficiente"] = lm.coef_

coef_df